# Generated by Django 3.2 on 2023-02-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('eur', 'eur')], max_length=127, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Единица товара',
                'verbose_name_plural': 'Единицы товара',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('eur', 'eur')], max_length=127, verbose_name='Валюта')),
                ('items', models.ManyToManyField(to='payments.Item', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
